# Generated by Django 5.2.8 on 2025-12-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='dicreption',
            field=models.TextField(blank=True),
        ),
    ]
