# Generated by Django 5.2.8 on 2025-12-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_todo_dicreption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='dicreption',
        ),
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
